name: liondance

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  intl: ^0.17.0
  url_launcher: ^6.0.20
  hive: ^2.1.0
  provider: ^6.0.2
  path_provider: ^2.0.9
  hive_generator: ^1.1.2
  crypto: ^3.0.1
  convert: ^3.0.1
  hive_flutter: ^1.1.0
  google_fonts: ^2.3.1
  caller: ^0.0.4
  flutter_easyrefresh: ^2.2.1
  cookie_jar: 3.0.1
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0  #latest version
  audioplayers: ^0.20.1
  flutter_svg: ^1.0.3
  flutter_launcher_icons: ^0.9.2
  adobe_xd: ^2.0.1
  encrypt: ^5.0.1

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: 'icon/ios.png'
  image_path_android: 'icon/android.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'icon/adaptive.png'

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
    - assets/design_course/
    - assets/fitness_app/
    - assets/hotel/

  fonts:
    - family: alibaba
      fonts:
        - asset: assets/fonts/Alibaba-PuHuiTi-Light.woff2

